version: "3"

services:

    mongodb:
        
        build: ./mongodb 
        container_name: mongodb_container
        volumes:
            - ./mongodb/data:/data/db
        ports:
            - '27018:27017'
        networks:
            - app-network

    python-app:
        
        build: ./python-app
        container_name: python_container
        restart: always
        volumes:
            - ./python-app:/app/server/python-app
        
        depends_on:
            - mongodb
        ports:
            - '8021:8020'

        networks:
            - app-network

networks: 
    app-network: 
          driver: bridge 


        
            
